### ISSUE TITLE
Connect! 

### ISSUE THREAD

**Issue by tiago1820** [tiago1820/proyecto-integrador#59]
It's time to connect the client with the server.

**Comment by tiago1820** [comment]
Very good! Now you have to do the same with the functions: registerUser and recoverPassword.

**Comment by Jefe94** [comment]
Very good! Now you have to do the same with the functions: registerUser and recoverPassword.

**Comment by tiago1820** [comment]
Yes, but first I have to create the endpoints on the backend server.

**Comment by Jefe94** [comment]
Go ahead!!!

**Comment by tiago1820** [comment]
All ready!
https://github.com/tiago1820/integrator-backend/commit/b4d7085f18476bc07a0f1db1efa28d7ee90fb7fb
